<div class="col-xs-12 col-sm-9 col-md-8 main-content">
 <section class="multi-line-signature">
  <span class="returntype">
   <a class="" href="dart-async/Future-class.html">
    Future
   </a>
   &lt;T&gt;
  </span>
  <span class="name ">
   singleWhere
  </span>
  (
  <wbr>
  <span class="parameter" id="singleWhere-param-test">
   <span class="type-annotation">
    bool
   </span>
   <span class="parameter-name">
    test
   </span>
   (
   <span class="parameter" id="test-param-element">
    <span class="type-annotation">
     T
    </span>
    <span class="parameter-name">
     element
    </span>
   </span>
   )
  </span>
  )
 </section>
 <section class="desc markdown">
  <p>
   Finds the single element in this stream matching
   <code>
    test
   </code>
   .
  </p>
  <p>
   Like
   <code>
    lastMatch
   </code>
   , except that it is an error if more than one
matching element occurs in the stream.
  </p>
 </section>
 <section class="summary source-code" id="source">
  <h2>
   <span>
    Source
   </span>
  </h2>
  <pre>
   <code class="prettyprint lang-dart">
    Future&lt;T&gt; singleWhere(bool test(T element)) {
  _Future&lt;T&gt; future = new _Future&lt;T&gt;();
  T result = null;
  bool foundResult = false;
  StreamSubscription subscription;
  subscription = this.listen(
    (T value) {
      _runUserCode(
        () =&gt; true == test(value),
        (bool isMatch) {
          if (isMatch) {
            if (foundResult) {
              try {
                throw IterableElementError.tooMany();
              } catch (e, s) {
                _cancelAndErrorWithReplacement(subscription, future, e, s);
              }
              return;
            }
            foundResult = true;
            result = value;
          }
        },
        _cancelAndErrorClosure(subscription, future)
      );
    },
    onError: future._completeError,
    onDone: () {
      if (foundResult) {
        future._complete(result);
        return;
      }
      try {
        throw IterableElementError.noElement();
      } catch (e, s) {
        _completeWithErrorCallback(future, e, s);
      }
    },
    cancelOnError: true);
  return future;
}
   </code>
  </pre>
 </section>
</div>
